export const articles = [
  {
    title: "10 Ways To Stay Healthy While Working A Crazy News Schedule",
    imageUrl: "/articles/image_1.png",
    date: "May 24, 2022",
    writer: "Soul Witness",
    likes: 35,
    comments: 25,
    shares: 15,
  },
  {
    title: "10 Ways To Stay Healthy While Working A Crazy News Schedule",
    imageUrl: "/articles/image_2.png",
    date: "June 10, 2022",
    writer: "Mindful Living",
    likes: 42,
    comments: 18,
    shares: 12,
  },
  {
    title: "10 Ways To Stay Healthy While Working A Crazy News Schedule",
    imageUrl: "/articles/image_3.png",
    date: "July 1, 2022",
    writer: "Nature Explorer",
    likes: 56,
    comments: 30,
    shares: 20,
  },
  {
    title: "10 Ways To Stay Healthy While Working A Crazy News Schedule",
    imageUrl: "/articles/image_4.png",
    date: "August 5, 2022",
    writer: "Foodie Delight",
    likes: 27,
    comments: 10,
    shares: 5,
  },
  {
    title: "10 Ways To Stay Healthy While Working A Crazy News Schedule",
    imageUrl: "/articles/image_1.png",
    date: "May 24, 2022",
    writer: "Soul Witness",
    likes: 35,
    comments: 25,
    shares: 15,
  },
]
